### ISSUE TITLE
Nelley's Game of Thrones

### ISSUE THREAD

**Issue by mrnelley** [ga-wdi-exercises/game_of_thrones#11]
https://github.com/mrnelley/Game-of-Thrones/
CRUD on all fours... Had trouble implementing the nested routes and broke everything. Checked out a new solution branch for JUST crud functionality. Saving CSS and styling for when nested relations work appropriately. 

Completeness: 3
Comprehension: 5

Comment: Fully understand rolls of MVC and getting sooo much better at navigating errors and getting off the ground with bonus features is great. Just flying anywhere once im off the ground is troublesome, ya know? 

Cant wait to literally put this next to this weeks homework AND next weeks project and show the amount of growth. That'll be cool.

**Comment by superbuggy** [comment]
comments in my PR! 👍
