### ISSUE TITLE
Ahmed's Lab 08/03

### ISSUE THREAD

**Issue by ahmedelk91** [ga-wdi-exercises/game_of_thrones#14]
Comfort: 4

Completeness: 4

Comments: I am really starting to like rails! After so much repetition I really feel that I'm getting the hang of the logic and process behind creating a fully functional CRUD app. Definitely need to work on styling. Will continue to improve! 

https://github.com/ahmedelk91/GoT_Lab

**Comment by superbuggy** [comment]
comments in my PR! 👍
