### ISSUE TITLE
GOT lab

### ISSUE THREAD

**Issue by BaVPhan** [ga-wdi-exercises/game_of_thrones#64]
Couldn't push to master branch for some reason.

Comfort: 3
Completeness: 3.5

Need more reps with Rails and Postgres

https://github.com/BaVPhan/GOTlab

**Comment by superbuggy** [comment]
👍  one comment really:

``` rb
    # consider naming this variable @houses_for_select to differentiate it from your other instance vars
    @houses = House.all.map {|house| [house.name, house.id]}
```
