### ISSUE TITLE
Tyler Rosenberg - Game of Thrones App

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/game_of_thrones#9]
Completeness: 3.7
Comfort: 4
https://github.com/TyRyanR/game_of_thrones

Felt WAYYY more comfortable creating a rails app after today. Today was such a struggle, learning the hard way how to do nested resources. By the end of the day my mind was completely done I couldn't focus anymore. I would have given myself a higher completeness score but I didn't get the chance to add any CSS. The functionality is all there however. I feel like I can do everything from scratch now, including flash notifications, validations, nested resources, partials...etc.

hodor

**Comment by ghost** [comment]
Hodor

**Comment by nayana487** [comment]
hold the door

**Comment by nayana487** [comment]
- might be good to add an option to delete, maybe also edit, a house on the main page
- nice work implementing nested resources, you did great!
- no big deal about the css, next step would be to add a third model
